### ISSUE TITLE
CreationExtras must have a value by SAVED_STATE_REGISTRY_OWNER_KEY` error

### ISSUE THREAD

**Issue by michaldrabik** [Syer10/voyager#1]
Regarding: https://github.com/adrielcafe/voyager/issues/86

Happens at val viewModel = getViewModel<...> seems like something to do with Transitions:

```
java.lang.IllegalArgumentException: CreationExtras must have a value by `SAVED_STATE_REGISTRY_OWNER_KEY`
                                                         	at androidx.lifecycle.SavedStateHandleSupport.createSavedStateHandle(SavedStateHandleSupport.kt:91)
                                                         	at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.java:89)
                                                         	at dagger.hilt.android.internal.lifecycle.HiltViewModelFactory.create(HiltViewModelFactory.java:116)
                                                         	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187)
                                                         	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153)
                                                         	at ***.IntroductionScreen.Content(IntroductionScreen.kt:315)
                                                         	at cafe.adriel.voyager.transitions.ComposableSingletons$SlideTransitionKt$lambda-1$1.invoke(SlideTransition.kt:30)
```

```
Navigator(ScreenRegistry.get(initialScreen)) { navigator ->
            SlideTransition(navigator)
...
}
```

**Comment by Syer10** [comment]
Closed by https://github.com/Syer10/voyager/commit/d91326791ae7df42dc7aadb1d4c7c7655cf50f6c

**Comment by Syer10** [comment]
Fixed in the latest release 👍 
It seems I missed a part of the HasDefaultViewModelProviderFactory, its now properly implemented and should work fine

**Comment by michaldrabik** [comment]
@Syer10 Unfortunately after trying latest rc05 the exact same issue remains.

**Comment by Syer10** [comment]
Hm, I wonder what else it could be then

**Comment by Syer10** [comment]
@michaldrabik Can you try using this function instead of the default one with my fork? I think it may fix it but I would like confirmation instead of releasing a possible fix that doesn't work

```kotlin
@Composable
public inline fun <reified T : ViewModel> Screen.getViewModel(
    viewModelProviderFactory: ViewModelProvider.Factory? = null
): T {
    val context = LocalContext.current
    return remember(key1 = T::class) {
        val activity = context.componentActivity
        val lifecycleOwner = (this as? ScreenLifecycleProvider)?.getLifecycleOwner() as? AndroidScreenLifecycleOwner
        val viewModelStore = lifecycleOwner?.viewModelStore ?: activity.viewModelStore
        val factory = VoyagerHiltViewModelFactories.getVoyagerFactory(
            activity = activity,
            owner = lifecycleOwner ?: activity,
            delegateFactory = viewModelProviderFactory
        )
        val provider = ViewModelProvider(
            store = viewModelStore, 
            factory = factory, 
            defaultCreationExtras = lifecycleOwner?.defaultViewModelCreationExtras ?: CreationExtras.Empty
        )
        provider[T::class.java]
    }
}
```

**Comment by michaldrabik** [comment]
Yes - it seems to does the trick.

**Comment by Syer10** [comment]
Its fixed in rc06 👍

**Comment by michaldrabik** [comment]
_Sorry for reopening again I think I led you to a premature celebration :) For some reason in our project everything works in one module but the same issue appeared again in another module/activity. I think it may have something to do with dependencies I will keep investigating._

I had mixed `Screen` with `AndroidScreen()` which casued the issue. Solved.
